### PR TITLE
Driver for network fixed

### PR DESCRIPTION
**Pull request by quantumde1**
Fixed driver for network

### CODE REVIEW

**Comment by Alex313031** [comment]
@quantumde1 I added this .ebuild from FydeOS, and used the firmware files from upstream Gentoo.

What is wrong with that one bin file that you want to remove it?

**Comment by quantumde1** [comment]
> @quantumde1 I added this .ebuild from FydeOS, and used the firmware files from upstream Gentoo.
> 
> What is wrong with that one bin file that you want to remove it?

bin from fydeOS ebuild not works. Idk why, but neither fydeos and your driver did not working, but this driver what im attached works pretty well

**Comment by Alex313031** [comment]
@quantumde1 But all you did was remove the .bin file, you didn't add the new one you are talking about. If you add a fixed .bin, I will merge it.

**Comment by quantumde1** [comment]
> @quantumde1 But all you did was remove the .bin file, you didn't add the new one you are talking about. If you add a fixed .bin, I will merge it.

hm. strange, im attached new.

**Comment by Alex313031** [comment]
@quantumde1 Can you add the new bin file and either update your pull request, or make a new one?

**Pull request merged**
